### ISSUE TITLE
Add an env var to your container. Call it FACTORIO_VERSION and give it the value 'stable'

### ISSUE THREAD

**Issue by RyleyRobinson** [OpenFactorioServerManager/factorio-server-manager#316]
Add an env var to your container. Call it FACTORIO_VERSION and give it the value 'stable'

_Originally posted by @Mattie112 in https://github.com/OpenFactorioServerManager/factorio-server-manager/issues/315#issuecomment-1053598476_

Hi @mattie112, thanks for the fast answer, I tried that, unfortunately no change

I found this https://www.factorio.com/download  according to this explanation I need server version 1.1.53

**Comment by makcuber** [comment]
Thanks for reposting this, dont think I would have found this solution otherwise. I had my env FACTORIO_VERSION value set to latest and couldn't connect to my server all of a sudden from Win 10. Seems the Linux Server latest version is 3 sub-versions ahead of the stable Win10 build Steam looks at. 

For anyone else that find this, I did have to use the latest autosave instead of the Load Latest option as the server had restarted using the newer server version and therefore upgraded the map data, rendering it incompatible with the "older" stable version. 

Lesson: Always use the 'stable' value for your FACTORIO_VERSION env value by default, not 'latest'.
