### ISSUE TITLE
How to include mods in a save? 

### ISSUE THREAD

**Issue by heath0xFF** [OpenFactorioServerManager/factorio-server-manager#380]
First, love the project. Makes handling a factorio sever painless. 

I am having a bit of trouble understanding mod management. I've got the space exploration mod installed, but when i create a save and launch a server, i'm required to sync mods and my factorio client disables the space exploration mod on the client side. 

I'm running FSM in a docker container on an ubuntu server with docker compose. 

I've tried: 
- restarting the server
- deleting and creating saves
- deleting and creating mod packs
- manually downloading and uploading the mod through the ui
- stopping and restarting the container 

what am i missing?

**Comment by knoxfighter** [comment]
Space exploration has a ton of dependencies, the server does not install dependencies itself, you have to manually do that. I suggest creating the save locally and then upload it. Then download the mods on the server with the feature "load mods from save". 
Since you just closed the issue, i guess you found it out yourself :)
