### ISSUE TITLE
Server instance not showing in Factorio

### ISSUE THREAD

**Issue by Baumbart13** [OpenFactorioServerManager/factorio-server-manager#383]
First, I tried to set up the docker container on my synology NAS, which works great, at least for the web-ui after configuring port-forwarding from Local port 8080 to container-port 80, as Environment-Variables cannot be passed to the conatiner (maybe synology-problem?), but i cannot see the factorio-server instance on my network. The port is the default one at 34197.

Same issue goes for, when i run the docker container on windows: The docker-Environment is still Linux, but I still have to forward my local port 8080 to dockers port 80, as I cannot change the port via Environment-variables.

So far, not a real issue.. which is, that also on a Windows-Host with a Docker-Container, I am not able to find the factorio-server instance. Changing the ports, docker is showing (forwarding), does not help. Neither can I connect to the server via IP-Address (localhost, 127.0.0.1 or my actual one). Is it something that I have overseen?

**Comment by Mattie112** [comment]
I don't really understand your question. Do you have a problem at Synology or at Windows (with Docker Desktop assuming?).

You need to map both the port for the web UI and the port for Factorio, are you doing that? Can you provide some screenshots?

For Windows you possible need to run the server on `0.0.0.0` (if it is not already doing that) or connect to the IP of the container instead of localhost. But then again if the web-interface works....

A couple of screenshots or details from Docker could help.

**Comment by Baumbart13** [comment]
Thanks @Mattie112 for further questioning an more specifying my problem, but I've found my issue in the meantime:

As the server is starting and running, it takes a few moments - sometimes even longer - to run the gameserver.

An indicator for seeing, if the gameserver itself is running, would be neat, to see if the is really running or just starting up
