### ISSUE TITLE
Mod configurations

### ISSUE THREAD

**Issue by jelutz77** [OpenFactorioServerManager/factorio-server-manager#393]
When I uploaded my save and all mods, I tried to start and received the message "Mod startup settings mismatch", and I'm offered the chance to apply the server's startup settings and restart the game, which I will not do. How can I apply the client's settings to the server?

**Comment by Mattie112** [comment]
If I remember correctie FSM does not (always) fetch dependencies for mods. Most simple solution would be to copy the mods from your PC to the server then it should match.

**Comment by jelutz77** [comment]
I also noticed that not all the mods came over when I told it to get the mods from the save. I was prompted to sync mods, but I worked through that and uploaded all the rest of the mods. This issue is different, and I believe it’s related to the mod configurations I had set up in the client.

Or are you saying that this may be because I had loaded some from the store and some via upload, and I should upload all mods that I configured with the client? Are the mod configurations stored in the mod zip file?

**Comment by Mattie112** [comment]
Yeah I think I also recall that issue. So on your server you are running the save you created on your PC?

I'll try to stretch my brain-cells to see if I remember the issue I was having.

**Comment by jelutz77** [comment]
Yes, uploaded the save from my PC.

**Comment by knoxfighter** [comment]
Easiest way to get the mods on the server if you have a more complex mod setup and settings is to do it manually into the server filesystem. That means, uploading the whole local mod directory with mod.settings and such directly into the mods directory of the server (via ssh or other tools). The mod support of the fsm is only rudimentary and has issues when doing the first setup. Doing updates with it works great.

**Comment by Squelch** [comment]
The problem lies in how the mods are being parsed. Each mod's `info.json` is being checked for dependencies, but FSM has not been updated, so is unaware of the newer dependency flags. ie It checks for only 3 parts of the dependency string as -  dependency name, comparitor and version. The flags prefix the name creating 4 parts of the string, so as a result, FSM sees the dependency as optional or incorrectly formatted and then skips (ignores) the actual dependency. 

Tilde  "~" is particularly problematic as it denotes a required dependency, but does not enforce a load order. FSM simply ignores this directive and fails to fetch the requirement.

I encountered this a week ago after one dependency update was interrupted, and failed to load. I was unable to reinstate the file, so removed and reinstalled the docker container afresh. Now, even after uploading a working desktop save, and the complete mod folder, I have a mod mismatch when attempting to connect. A large number of dependencies are aledged to be missing from the save. Copying back the servers save and mods to the desktop shows no problem. I simply cannot fathom why, but feel it is somehow related to mod-ilist.info being rewritten. Formatting is slightly different between a fresh destop version and one that FSM creates. However, the FSM version loads fine when copied to desktop.

**Comment by jelutz77** [comment]
I was able to get my mod settings updated by using ftp to transfer the mod-settings.json file from my client into the server’s config directory.

**Comment by Mattie112** [comment]
Yes that should work if I recall correctly!
