### ISSUE TITLE
Mod search is broken (probably by Wube)

### ISSUE THREAD

**Issue by dgw** [OpenFactorioServerManager/factorio-server-manager#91]
It is no longer possible to search for mods in the factorio-server-manager UI. I believe this is actually due to Wube launching the new, faster mod portal, since manually calling the API URL used by the app (`https://mods.factorio.com/api/mods?q=%s`) shows the same list of random mods as attempting a search in the app. There was talk of them breaking some API functions, and searching via the API seems to be one of them. I tried using the query parameters `q`, `query`, `search`, `k`, & `keyword` to no effect—all return the same unfiltered mod list.

This might not be immediately fixable as such, but it would be nice to be able to directly install a mod by typing in its mod portal name (i.e. `vanilla-loaders`, `Factorissimo2`, `PickerExtended`, etc. as those API queries seem to still work).

**Comment by knoxfighter** [comment]
This feature currently is broken/not implemented in the mod portal api
Reference: https://forums.factorio.com/viewtopic.php?f=189&t=56735&p=335714&hilit=+mod+portal+api+search#p335714

**Comment by dgw** [comment]
Yep, I thought as much. Any thoughts on directly installing mods by name, so we can at least search on the mod portal and then paste the name into the server manager to install directly without downloading and then uploading zip files?

**Comment by toonech** [comment]
This issue is further complicated because mods can have a different id than their display name, sometimes with underscores, hyphens, or nothing in place of a spaces.  

Like the top downloaded mod right now is Resource Spawner Overhaual, and it's id is 'rso-mod'.  Workaround I've been using is to find the mod in the mod portal, copy the url of the mod, paste the url in the search box, and then delete everything except the id.  

So for RSO, I'd paste in:

> https://mods.factorio.com/mod/rso-mod

and then delete everything so I'm left with: 

> rso-mod

To that end, can we update the code for the search feature to just parse the mod portal URLs so I can just paste in a URL and it's able to pull out the useful bits like I'm currently doing now manually?

**Comment by knoxfighter** [comment]
Fixed with #186. Will be added to the next release.
